apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
  labels:
    app: simple-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
      - name: simple-node
        image: silanka/simple_node_server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
