version: 2.1

jobs:
  build:
    working_directory: ./app
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0 awscli==1.11.76
      # - restore_cache:
      #     keys:
      #       - v1-{{ .Branch }}
      #     # paths:
      #     #   - /caches/app.tar
      # - run:
      #     name: Load Docker image Layer cache
      #     command: |
      #       set +o pipefail
      #       docker load -i /caches/app.tar | true
      - run:
          name: Build Application Docker image
          command: |
            docker build --cache-from=app -t $DOCKER_IMAGE_NAME .
      # - run:
      #     name: Save Docker image Layer cache
      #     command: |
      #       mkdir -p /caches
      #       docker save -o /caches/app.tar app
      # - save_cache:
      #     paths:
      #       - /caches/app.tar
      #     key: v1-{{ .Branch }}-{{ epoch }}
      - deploy:
          name: Push Application Docker image
          command: |
            if ["$ {CIRCLE_BRANCH}" == "main"]; then
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
            fi
