version: 2.1

jobs:
  build:
    working_directory: ./app
    docker:
      - image: docker:23.0-rc-cli
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Application Docker image
          command: |
            docker build --cache-from=$DOCKER_IMAGE_NAME -t $DOCKER_IMAGE_NAME .
      - deploy:
          name: Push Application Docker image
          command: |
            if ["$ {CIRCLE_BRANCH}" == "main"]; then
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
            fi
